### ISSUE TITLE
Does not function as per example

### ISSUE THREAD

**Issue by njho** [mohithg/react-typeform#2]
Anyone else have luck?

I tried integrating it into an existing app and it wasn't functioning properly.

**Comment by mohithg** [comment]
@njho can you put your code into a fiddle, I can help you fix it

**Comment by chris247474** [comment]
I'm having trouble as well. Whenever I run this code:

`<Typeform onSubmit={this.submit}>
          <Input type='text' label='Name' name='name' value={this.state.name} onChange={this.handleChange} maxLength={16 } />
        </Typeform>`

i get Warning: Unknown prop `tfStyle` @mohithg any suggestions?

**Comment by mohithg** [comment]
@ctverceles `<Typeform onSubmit={this.submit}> <div> <Input type='text' label='Name' name='name' value={this.state.name} onChange={this.handleChange} maxLength={16 } /> </div>
 </Typeform>` please wrap specific input components into div, actually the warning is throwing from your `Input` since your `Input` throws warning if extra props are used.

**Comment by mohithg** [comment]
Closing issue, since there is no response. Assuming its fixed.
